# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import util
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(867, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(30, 200, 93, 28))
        self.openButton.setObjectName("openButton")
        self.showImage = QtWidgets.QLabel(self.centralwidget)
        self.showImage.setGeometry(QtCore.QRect(220, 30, 551, 451))
        self.showImage.setObjectName("showImage")
        self.predict_result = QtWidgets.QLabel(self.centralwidget)
        self.predict_result.setGeometry(QtCore.QRect(360, 580, 72, 15))
        self.predict_result.setObjectName("predict_result")
        self.Notelabel = QtWidgets.QLabel(self.centralwidget)
        self.Notelabel.setGeometry(QtCore.QRect(230, 580, 91, 16))
        self.Notelabel.setObjectName("Notelabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openButton.setText(_translate("MainWindow", "选取图片"))
        self.predict_result.setText(_translate("MainWindow", "Loading.."))
        self.Notelabel.setText(_translate("MainWindow", "预测结果为："))
